#ifndef PLAYER_H
#define PLAYER_H

#include "types.h"
#include "enums.h"
#include "forward_declarations.h"

#pragma pack(push, 1)
struct Player {
    struct Player *CurrentPlayer;
    struct Player *Player;
    struct KeyPlayer Rotate;
    struct FW FW;
    struct S103 *S103;
    int16_t Sw;
    int16_t TypeWeapon;
    struct S103 *S103_1;
    int16_t SelectWeaponNext;
    char field_1E;
    char field_1F;
    struct S103 *pS103;
    int ID;
    struct S103 *S103_2;
    int16_t MoneyValue;
    uint8_t Ids;
    char field_2F;
    struct S103 *S103_5;
    struct Gangs *RESPECT;
    struct S103 *field_38;
    int field_3C;
    struct S103 *S103_4;
    enum DEATH_REASON DeathReason;
    struct Tango *Tango1;
    int Sound;
    int field_50;
    int field_54;
    int field_58;
    struct Car *sCar1;
    int field_60;
    int field_64;
    int MultiPlayerMode;
    int field_6C;
    uint8_t Up;
    uint8_t Down;
    uint8_t Left;
    uint8_t Right;
    uint8_t prevWeapon;
    uint8_t nextWeapon;
    uint8_t debugKey1;
    uint8_t debugKey2;
    bool Forward;
    bool Backward;
    bool RotateLeft;
    bool RotateRight;
    bool Attack;
    bool Enter;
    bool Jump;
    bool NextWeaponZ;
    bool PrevWeaponX;
    bool keySpecial;
    bool keySpecial2;
    char field_83;
    int field_84;
    int field_88;
    char AttackIsChanged;
    char field_8D;
    uint8_t PlayerNext;
    char field_8F;
    struct CameraOrPhysics *CameraOrPhysics1;
    char field_94;
    char field_95;
    char field_96;
    char field_97;
    int State;
    struct AudioManager *AudioManager;
    int field_A0;
    char gapA4[3];
    char field_A7;
    char field_A8;
    char field_A9;
    uint8_t sbw;
    uint8_t tpa;
    char field_AC;
    char gapAD[11];
    struct S131 *S1__;
    char gapBC[23];
    char field_D3;
    char gapD4[7];
    char field_DB;
    char gapDC[14];
    char field_EA;
    char gapEB[12];
    char field_F7;
    char gapF8[10];
    char field_102;
    char gap103[18];
    char field_115;
    char field_116;
    char field_117;
    int field_118;
    int field_11C;
    int field_120;
    char field_124;
    char field_125;
    char field_126;
    char field_127;
    int field_128;
    int field_12C;
    int field_130;
    char gap134[24];
    struct CameraOrPhysics *CameraOrPhysics;
    char gap150[4];
    char field_154;
    char gap155[62];
    char field_193;
    char gap194[18];
    char field_1A6;
    char gap1A7[32];
    char field_1C7;
    char gap1C8[9];
    char field_1D1;
    int field_1D4;
    int field_1D8;
    int field_1DC;
    char gap1E0[4];
    int Camer_X_View;
    int Camer_Y_View;
    int Camer_Z_View;
    char gap1F0[3];
    char field_1F3;
    char gap1F4[6];
    char field_1FA;
    char gap1FB[7];
    char field_202;
    char gap203[5];
    struct CameraOrPhysics *CameraOrPhysics2;
    char field_20C;
    char gap20D[28];
    char field_229;
    char gap22A[35];
    char field_24D;
    char gap24E[11];
    char field_259;
    char gap25A[17];
    char field_26B;
    char gap26C[32];
    char field_28C;
    char gap28D[11];
    char field_298;
    char gap299[5];
    char field_29E;
    char field_29F;
    int AuxGameCameraX;
    int AuxGameCameraY;
    int AuxGameCameraZ;
    char gap2AC[24];
    struct Ped *MainPed;
    struct Ped *pPassenger;
    struct Car *sCar2;
    char field_2D0;
    struct S161 *Money;
    char gap2D8[107];
    char field_343;
    char gap344[160];
    char field_3E4;
    char gap3E5[53];
    char field_41A;
    char gap41B[46];
    char field_449;
    char gap44A[31];
    char field_469;
    char field_46A;
    char field_46B;
    char field_46C;
    char field_46D;
    char field_46E;
    char field_46F;
    char field_470;
    char field_471;
    char field_472;
    char field_473;
    char field_474;
    char field_475;
    char field_476;
    char field_477;
    char field_478;
    char field_479;
    char field_47A;
    char field_47B;
    char field_47C;
    char field_47D;
    char field_47E;
    char field_47F;
    char field_480;
    char gap481[9];
    char field_48A;
    char gap48B[437];
    char field_640;
    int field_644;
    char gap648[48];
    int field_678;
    int field_67C;
    uint16_t field_680;
    int16_t field_682;
    struct S161 *Lives;
    char gap688[52];
    struct S161 *MultiPlayer;
};
#pragma pack(pop)

// Player function declarations
Player* Game__Game_FUN_003f11a8(Game *this);

#endif // PLAYER_H
